"""Stable failure taxonomy; technical failures are never trade verdicts."""
from __future__ import annotations

from dataclasses import dataclass
from enum import Enum


class FailureCode(str, Enum):
    INPUT_SCHEMA_REJECTED = "INPUT_SCHEMA_REJECTED"
    INPUT_FUTURE_DATED = "INPUT_FUTURE_DATED"
    INPUT_STALE = "INPUT_STALE"
    INPUT_EXPIRED = "INPUT_EXPIRED"
    ARTIFACT_MISSING = "ARTIFACT_MISSING"
    ARTIFACT_HASH_MISMATCH = "ARTIFACT_HASH_MISMATCH"
    ARTIFACT_SIZE_MISMATCH = "ARTIFACT_SIZE_MISMATCH"
    ARTIFACT_PATH_REJECTED = "ARTIFACT_PATH_REJECTED"
    MANIFEST_HASH_MISMATCH = "MANIFEST_HASH_MISMATCH"
    BUNDLE_HASH_MISMATCH = "BUNDLE_HASH_MISMATCH"
    REQUIRED_EVIDENCE_MISSING = "REQUIRED_EVIDENCE_MISSING"
    DUPLICATE_CONFLICT = "DUPLICATE_CONFLICT"
    OPENCLAW_UNAVAILABLE = "OPENCLAW_UNAVAILABLE"
    AUTHENTICATION_UNAVAILABLE = "AUTHENTICATION_UNAVAILABLE"
    RATE_LIMITED = "RATE_LIMITED"
    MODEL_TIMEOUT = "MODEL_TIMEOUT"
    MODEL_UNAVAILABLE = "MODEL_UNAVAILABLE"
    SESSION_FAILURE = "SESSION_FAILURE"
    MALFORMED_MODEL_OUTPUT = "MALFORMED_MODEL_OUTPUT"
    OUTPUT_SCHEMA_FAILURE = "OUTPUT_SCHEMA_FAILURE"
    IDENTIFIER_MISMATCH = "IDENTIFIER_MISMATCH"
    EVIDENCE_REFERENCE_MISMATCH = "EVIDENCE_REFERENCE_MISMATCH"
    RR_FAILURE = "RR_FAILURE"
    SPREAD_FAILURE = "SPREAD_FAILURE"
    EXPIRY_FAILURE = "EXPIRY_FAILURE"
    ENVIRONMENT_FAILURE = "ENVIRONMENT_FAILURE"
    MODIFY_SCOPE_FAILURE = "MODIFY_SCOPE_FAILURE"
    AUDIT_PERSISTENCE_FAILURE = "AUDIT_PERSISTENCE_FAILURE"
    CONCURRENT_IN_FLIGHT = "CONCURRENT_IN_FLIGHT"
    UNSUPPORTED_PROMPT_VERSION = "UNSUPPORTED_PROMPT_VERSION"
    CONFIG_INVALID = "CONFIG_INVALID"
    CANCELLED = "CANCELLED"


@dataclass(frozen=True)
class ReviewFailure(Exception):
    code: FailureCode
    message: str
    retryable: bool = False
    category: str = "TECHNICAL_FAILURE"

    def __str__(self) -> str:
        return f"{self.code.value}: {self.message}"


class InputRejected(ReviewFailure):
    def __init__(self, code: FailureCode, message: str):
        super().__init__(code, message, False, "INPUT_REJECTION")


class TechnicalFailure(ReviewFailure):
    pass
