"""Frozen Project A contract registry and validation helpers."""

from .registry import (
    AI_VERDICT_SCHEMA_V1,
    ANALYSIS_REQUEST_SCHEMA_V1,
    EVENT_SCHEMA_V0_2,
    PROJECT_A_CANONICAL_EVENT_V1,
    PROJECT_A_WIRE_EVENT_V1,
    THESIS_SCHEMA_V1,
)
from .event_v1 import (
    CanonicalEventV1Document,
    CanonicalVerificationResultV1,
    DedupeAuthority,
    DedupeDecision,
    DedupeReceiptTransaction,
    InMemoryDedupeAuthority,
    ParsedWireEventV1,
    ReceiptProcessingResultV1,
    canonicalize_wire_event_v1,
    consume_point_of_use_authorization,
    parse_wire_event_v1_bytes,
    process_wire_event_v1_receipt,
    process_wire_event_v1_receipt_in_transaction,
    read_project_a_event,
    semantic_evidence_projection,
    validate_canonical_event_v1,
    validate_canonical_event_v1_shape,
    validate_legacy_event_v0_2,
    validate_wire_event_v1,
    validate_wire_event_v1_shape,
    verify_and_authorize_canonical_event_v1,
)
from .validation import ContractError, canonical_json, canonical_json_bytes, validate_contract

__all__ = [
    "AI_VERDICT_SCHEMA_V1",
    "ANALYSIS_REQUEST_SCHEMA_V1",
    "CanonicalEventV1Document",
    "CanonicalVerificationResultV1",
    "ContractError",
    "DedupeAuthority",
    "DedupeDecision",
    "DedupeReceiptTransaction",
    "EVENT_SCHEMA_V0_2",
    "PROJECT_A_CANONICAL_EVENT_V1",
    "PROJECT_A_WIRE_EVENT_V1",
    "InMemoryDedupeAuthority",
    "ParsedWireEventV1",
    "ReceiptProcessingResultV1",
    "THESIS_SCHEMA_V1",
    "canonical_json",
    "canonical_json_bytes",
    "canonicalize_wire_event_v1",
    "consume_point_of_use_authorization",
    "parse_wire_event_v1_bytes",
    "process_wire_event_v1_receipt",
    "process_wire_event_v1_receipt_in_transaction",
    "read_project_a_event",
    "semantic_evidence_projection",
    "validate_canonical_event_v1",
    "validate_canonical_event_v1_shape",
    "validate_contract",
    "validate_legacy_event_v0_2",
    "validate_wire_event_v1",
    "validate_wire_event_v1_shape",
    "verify_and_authorize_canonical_event_v1",
]
